### ISSUE TITLE
Can't make the app work

### ISSUE THREAD

**Issue by thomasarsouze** [RamiALBASHA/fete_de_la_science#1]
Hi Rami,

I can't make the application work.
Can you specify the workflow to make it work correctly ? Looking at the code, I can't see any call to the `run_hydroshoot` function, so it seems to be necessary to run it prior to launching the app, is it right ? Is it normal and intended behaviour ?
I've also tried `python models/sim_funcs.py` but I've got a problem with some arguments calls.

Thanks for your help !

**Comment by RamiALBASHA** [comment]
Hello Thomas,
Thak you for the question.
Part of the problems comes from uncommitted modifications that I have just pushed and merged into `main`.
I have created a README.md for installation and usage procedures. Please tell me if this works for you.
Best,
Rami

**Comment by thomasarsouze** [comment]
Hi,
thanks for your reactivity !
Unfortunately, I've tried on both branches, but I got the same error: 
```
END: {"recalculating": {"name": "display_3d_canopy1", "status": "recalculating"}}
SEND: {"busy": "busy"}
Traceback (most recent call last):
  File "/Users/arsouze/miniconda3/envs/openalea/lib/python3.9/site-packages/shiny/session/_session.py", line 1022, in output_obs
    message[output_name] = fn()
  File "/Users/arsouze/miniconda3/envs/openalea/lib/python3.9/site-packages/shinywidgets/_shinywidgets.py", line 198, in __call__
    return run_coro_sync(self.run())
  File "/Users/arsouze/miniconda3/envs/openalea/lib/python3.9/site-packages/shiny/_utils.py", line 216, in run_coro_sync
    coro.send(None)
  File "/Users/arsouze/miniconda3/envs/openalea/lib/python3.9/site-packages/shinywidgets/_shinywidgets.py", line 201, in run
    x = await self._fn()
  File "/Users/arsouze/miniconda3/envs/openalea/lib/python3.9/site-packages/shiny/_utils.py", line 171, in fn_async
    return fn(*args, **kwargs)
  File "/Users/arsouze/Documents/Modeles/Simulations/OpenAlea/shinyapp-rami/models/app.py", line 241, in display_3d_canopy1
    return sim_funcs.show_3d_canopy(canopy_name=ui_input.canopy_1(), is_complete_canopy=True)
  File "/Users/arsouze/Documents/Modeles/Simulations/OpenAlea/shinyapp-rami/models/sim_funcs.py", line 423, in show_3d_canopy
    return PlantGL(virtual_scene)
  File "/Users/arsouze/miniconda3/envs/openalea/lib/python3.9/site-packages/oawidgets-1.0.0-py3.9.egg/oawidgets/plantgl.py", line 176, in PlantGL
    meshes = group_meshes_by_color(pglobject)
  File "/Users/arsouze/miniconda3/envs/openalea/lib/python3.9/site-packages/oawidgets-1.0.0-py3.9.egg/oawidgets/plantgl.py", line 158, in group_meshes_by_color
    meshes_scene.extend(meshes_crv)
UnboundLocalError: local variable 'meshes_crv' referenced before assignment
SEND: {"recalculating": {"name": "display_3d_canopy1", "status": "recalculated"}}
SEND: {"busy": "idle"}
SEND: {"recalculating": {"name": "display_3d_canopy2", "status": "recalculating"}}
```

**Comment by RamiALBASHA** [comment]
This looks like a problem that I have already highlighted in the 'oawidgets' package

https://github.com/openalea-incubator/oawidgets/pull/23#issuecomment-1307013185

It should have been solved though..
Could you check out whether you have the fixed oawidgets version (I have 1.0.0) ?

**Comment by thomasarsouze** [comment]
Ok, probably a conda / pip mess in my environment... anyway, I managed to go one step further:
```
RECV: {"method":"update","data":{"plot_mtg:shiny.action":1}}
SEND: {"progress": {"type": "binding", "message": {"id": "display_mtg_property"}}}
SEND: {"busy": "busy"}
SEND: {"recalculating": {"name": "display_mtg_property", "status": "recalculating"}}
Traceback (most recent call last):
  File "/Users/arsouze/miniconda3/envs/openalea/lib/python3.9/site-packages/shiny/session/_session.py", line 1022, in output_obs
    message[output_name] = fn()
  File "/Users/arsouze/miniconda3/envs/openalea/lib/python3.9/site-packages/shiny/render/_render.py", line 206, in __call__
    return _utils.run_coro_sync(self._run())
  File "/Users/arsouze/miniconda3/envs/openalea/lib/python3.9/site-packages/shiny/_utils.py", line 216, in run_coro_sync
    coro.send(None)
  File "/Users/arsouze/miniconda3/envs/openalea/lib/python3.9/site-packages/shiny/render/_render.py", line 222, in _run
    x = await self._fn()
  File "/Users/arsouze/miniconda3/envs/openalea/lib/python3.9/site-packages/shiny/_utils.py", line 171, in fn_async
    return fn(*args, **kwargs)
  File "/Users/arsouze/miniconda3/envs/openalea/lib/python3.9/site-packages/shiny/reactive/_reactives.py", line 836, in new_user_fn
    return user_fn()
  File "/Users/arsouze/Documents/Modeles/Simulations/OpenAlea/shinyapp-rami/models/app.py", line 206, in display_mtg_property
    return sim_funcs.plot_mtg_property(
  File "/Users/arsouze/Documents/Modeles/Simulations/OpenAlea/shinyapp-rami/models/sim_funcs.py", line 350, in plot_mtg_property
    with open(path_ref_1, mode='rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/arsouze/Documents/Modeles/Simulations/OpenAlea/shinyapp-rami/models/data/output_ref/vsp/mtg20120801120000.pckl'
```

**Comment by RamiALBASHA** [comment]
This is due to the fact that hydroshoot's outputs were not generated. Those outputs are necessary for visualizing preprocessed results.
Could you please run `sim_funcs.py` and tell me if data/output_ref directory is generated ?

**Comment by thomasarsouze** [comment]
Nope, I only get an empty `data/output_user` directory.
Also, note that to make it run with no error, I had to change (`path_weather` and `user_params` not specified) from :
```
l89.     inputs = io.HydroShootInputs(g=grapevine_mtg, path_project=path_project_dir, scene=scene, psi_soil=psi_soil,
```
to
```
l89.     inputs = io.HydroShootInputs(g=grapevine_mtg, path_project=path_project_dir, path_weather=path_project_dir, scene=scene, user_params={}, psi_soil=psi_soil,
```

**Comment by RamiALBASHA** [comment]
I forgot to specify that HydroShoot's version is 4.0.0. Thanks for highlighting this matter.
I have cloned and run the script from scratch and performed bugfix and refactos.
Please switch to v.4.0.0 and tell me if everthing works now.

**Comment by thomasarsouze** [comment]
Here we are !!! Now works fine.
Thanks for the updates.
